# /home/bill/.config/alacritty/alacritty.toml
# Bill Waller

[terminal.shell]
program = "/usr/local/bin/xsh"

[general]

# import = [
#     "~/.config/alacritty/fonts/default_font",
# BEGIN_ALACRITTY_FONT
[font]
normal = { family = "JetBrainsMono NFM", style = "Medium" }
bold = { family = "JetBrainsMono NFM", style = "ExtraBold" }
italic = { family = "JetBrainsMono NFM", style = "Italic" }
bold_italic = { family = "JetBrainsMono NFM", style = "Bold Italic" }
# END_ALACRITTY_FONT
#     "~/.config/alacritty/themes/default_theme.toml",
[colors.primary]
background  = '#000000'
foreground  = '#c0c0c0'

[colors.normal]
black       = '#000000'
red         = '#ff2f00'
green       = '#4ff07f'
yellow      = '#ffef4f'
blue        = '#5fafff'
magenta     = '#f077f0'
cyan        = '#8fdfff'
white       = '#ff5f00'
[colors.bright]
black       = '#bfbfbf'
red         = '#ff5f00'
green       = '#00FFa0'
yellow      = '#FFcf00'
blue        = '#005fff'
magenta     = '#FF00FF'
cyan        = '#00ffff'
white       = '#e0d0d0'
# ]

[font]
size = 17

# dynamic_title = true
# decorations = "Full"
# decorations_theme_variant = "Dark"

[window]
dimensions = { columns = 95, lines = 67 }

[scrolling]
history = 10000
