# /home/bill/.config/alacritty/alacritty.toml
# Alacritty Configuration File
# Bill Waller

[general]
 
import = [
  "~/.config/alacritty/fonts/default_font.toml",
  "~/.config/alacritty/themes/default_theme.toml",
]

[font]
size = 14

# dynamic_title = true
# decorations = "Full"
# decorations_theme_variant = "Dark"

[window]
dimensions = { columns = 88, lines = 40 }

[scrolling]
history = 10000


# import = [
#   "~/.config/alacritty/fonts/default_font.toml",
# BEGIN_ALACRITTY_FONT
[font]
normal = { family = "Source Code Pro", style = "Regular" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }
# END ALACRITTY_FONT
#   "~/.config/alacritty/themes/default_theme.toml",
[colors.primary]
background  = '#000000'
foreground  = '#c0c0c0'

[colors.normal]
black       = '#000000'
red         = '#FF0000'
green       = '#00FF8f'
yellow      = '#FFc700'
blue        = '#009FFF'
magenta     = '#e070e0'
cyan        = '#00CFDF'
white       = '#FF7f00'
[colors.bright]
black       = '#7f7f7f'
red         = '#FF7F00'
green       = '#00FFa0'
yellow      = '#FFEf00'
blue        = '#0000FF'
magenta     = '#FF00FF'
cyan        = '#00ffff'
white       = '#FFFFFF'
# ]
